### ISSUE TITLE
Serving a website and its websocket

### ISSUE THREAD

**Issue by cardinal-II** [ngrok/ngrok#21]
Is it possible to use ngrok (free plan) for serving a website and its websocket (at the same port) simultaneously?

Now I can expose only a website. Its websocket doesn't work, unfortunately. I got the error: Firefox can’t establish a connection to the server at wss://abc.ngrok-free.app/.

**Comment by russorat** [comment]
Hi @cardinal-II, you can create up to 3 tunnels with the same agent on the free tier. You can leverage edges and routes to say something like "abc.ngrok-free.app/ routes to the website, abc.ngrok-free.app/websocket routes to the websocket".

would that work for you? otherwise, you could create 3 tunnels with the same agent and 3 different domains.

**Comment by cardinal-II** [comment]
I am trying this in the config file:
```yaml
version: "2"
authtoken: 2Wn
tunnels:
  website:
    addr: 3011
    proto: http
    domain: abc.ngrok-free.app

  websocket:
    addr: 3011
    proto: tcp
    domain: abc.ngrok-free.app/websocket
```
But after running the command `ngrok start --all`, I got the error: `line 12: field domain not found in type config.TCPv2Tunnel`.

**Comment by russorat** [comment]
It's a little more involved than that unfortunately (although we are trying to make it much easier in the future).

In order to get path based routing, you will need to use ngrok edges. I'll try to walk you through it.

First, you will need to use the ngrok api, so if you haven't already, log into dashboard.ngrok.com, generate an API key in the API section on the left side, and install it into your ngrok cli tool using `ngrok config add-api-key THE_KEY_FROM_DASH`. This allows you to use the `ngrok api` function.

1. Next, make sure you've got your domain handy using `ngrok api reserved-domains list`.

```json
200 OK
{
  "next_page_uri": null,
  "reserved_domains": [
    {
      "acme_challenge_cname_target": null,
      "certificate": null,
      "certificate_management_policy": null,
      "certificate_management_status": null,
      "cname_target": null,
      "created_at": "2024-08-02T22:42:37Z",
      "domain": "buffalo-organic-happily.ngrok-free.app",
      "error_redirect_url": null,
      "http_endpoint_configuration": null,
      "https_endpoint_configuration": null,
      "id": "rd_2k7dTcP1yxiA56r5nFlzVEZHuEa",
      "region": "",
      "uri": "https://api.ngrok.com/reserved_domains/rd_2k7dTcP1yxiA56r5nFlzVEZHuEa"
    }
  ],
  "uri": "https://api.ngrok.com/reserved_domains"
}
```
If you don't have one, you can claim it in the ngrok dashboard as well.

2. Create your ngrok edge using your domain: `ngrok api edges https create --description "my edge" --hostports "YOUR_DOMAIN:443"`
```json
201 Created
{
  "created_at": "2024-08-02T23:10:46Z",
  "description": "my edge",
  "hostports": [
    "buffalo-organic-happily.ngrok-free.app:443"
  ],
  "id": "edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ",
  "mutual_tls": null,
  "routes": [],
  "tls_termination": null,
  "uri": "https://api.ngrok.com/edges/https/edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ"
}
```

3. Export the `id` value as a new environment variable named `NGROK_EDGE_ID`:

`export NGROK_EDGE_ID=your-edge-id`

4. Create your first tunnel group backend to connect to your website: 

`ngrok api backends tunnel-group create --labels service=website --description "website tunnel"`

```json
201 Created
{
  "created_at": "2024-08-02T23:14:10Z",
  "description": "website tunnel",
  "id": "bkdtg_2k7hJXFrLUJzYXVjFoXUhRsGxVp",
  "labels": {
    "service": "website"
  },
  "tunnels": [],
  "uri": "https://api.ngrok.com/backends/tunnel_group/bkdtg_2k7hJXFrLUJzYXVjFoXUhRsGxVp"
}
```

5. Export the `id` value as a new environment variable named `NGROK_WEBSITE_BACKEND_ID`

`export NGROK_WEBSITE_BACKEND_ID=your-tunnel-group-id`

6. Create your second tunnel group backend to connect to your websocket: 

`ngrok api backends tunnel-group create --labels service=websocket --description "websocket tunnel"`

```json
201 Created
{
  "created_at": "2024-08-02T23:17:34Z",
  "description": "websocket tunnel",
  "id": "bkdtg_2k7hjCCZSMW7vK4xW22JiEzB1HL",
  "labels": {
    "service": "websocket"
  },
  "tunnels": [],
  "uri": "https://api.ngrok.com/backends/tunnel_group/bkdtg_2k7hjCCZSMW7vK4xW22JiEzB1HL"
}
```

7. Export the `id` value as a new environment variable named `NGROK_WEBSOCKET_BACKEND_ID`

`export NGROK_WEBSOCKET_BACKEND_ID=your-tunnel-group-id`

8. Create your first base route for your website on the `/` path :

`ngrok api edges https-routes create ${NGROK_EDGE_ID} --backend.backend-id ${NGROK_WEBSITE_BACKEND_ID} --match "/" --match-type path_prefix`

```json
201 Created
{
  "backend": {
    "backend": {
      "id": "bkdtg_2k7hJXFrLUJzYXVjFoXUhRsGxVp",
      "uri": "https://api.ngrok.com/backends/tunnel_group/bkdtg_2k7hJXFrLUJzYXVjFoXUhRsGxVp"
    },
    "enabled": true
  },
  "circuit_breaker": null,
  "compression": null,
  "created_at": "2024-08-02T23:19:07Z",
  "edge_id": "edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ",
  "id": "edghtsrt_2k7hunPmmV9J3L8dDGccxcVvgTJ",
  "ip_restriction": null,
  "match": "/",
  "match_type": "path_prefix",
  "oauth": null,
  "oidc": null,
  "policy": null,
  "request_headers": null,
  "response_headers": null,
  "saml": null,
  "traffic_policy": null,
  "uri": "https://api.ngrok.com/edges/https/edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ/routes/edghtsrt_2k7hunPmmV9J3L8dDGccxcVvgTJ",
  "user_agent_filter": null,
  "webhook_verification": null,
  "websocket_tcp_converter": null
}
```

9. Create your second route for your websocket service on the `/websocket` path: 

`ngrok api edges https-routes create ${NGROK_EDGE_ID} --backend.backend-id ${NGROK_WEBSOCKET_BACKEND_ID} --match "/websocket" --match-type path_prefix`

```json
201 Created
{
  "backend": {
    "backend": {
      "id": "bkdtg_2k7hjCCZSMW7vK4xW22JiEzB1HL",
      "uri": "https://api.ngrok.com/backends/tunnel_group/bkdtg_2k7hjCCZSMW7vK4xW22JiEzB1HL"
    },
    "enabled": true
  },
  "circuit_breaker": null,
  "compression": null,
  "created_at": "2024-08-02T23:20:38Z",
  "edge_id": "edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ",
  "id": "edghtsrt_2k7i6KhPmjSwsqWAKOwuYBsxenl",
  "ip_restriction": null,
  "match": "/websocket",
  "match_type": "path_prefix",
  "oauth": null,
  "oidc": null,
  "policy": null,
  "request_headers": null,
  "response_headers": null,
  "saml": null,
  "traffic_policy": null,
  "uri": "https://api.ngrok.com/edges/https/edghts_2k7gtpYcBXR4IRVbamBwAOxQjlZ/routes/edghtsrt_2k7i6KhPmjSwsqWAKOwuYBsxenl",
  "user_agent_filter": null,
  "webhook_verification": null,
  "websocket_tcp_converter": null
}
```

10. Finally you're ready to configure your agent to connect to the edge (assuming your website is running on localhost:80 and your websocket is on localhost:3011):

```yaml
api_key: XXX
authtoken: XXX
version: "2"
tunnels:
    website:
        labels:
          - service=website
        addr: 80
    websocket:
        labels:
          - service=websocket
        addr: 3011
```

Then run `ngrok start --all` and you should have two tunnels connecting to your edge:

```
Forwarding                    tn_2k7imNpnmk6c8ovRvK3hF4dcE9f (service=websocket) -> tcp://localhost:3011
Forwarding                    tn_2k7imQZXXqppVZor8vpkk6YVs5M (service=website) -> http://localhost:80
```

If you log into your dashboard, you should see your new edge, with your agent connected: https://dashboard.ngrok.com/cloud-edge/edges/ (might have to refresh)

**Comment by cardinal-II** [comment]
Thank you for your clear instruction. Everything is working except one thing. The website and websocket have the same port (3011). So I specified that in the config file:

```
api_key: XXX
authtoken: XXX
version: "2"
tunnels:
    website:
        labels:
          - service=website
        addr: 3011 <---- not 80
    websocket:
        labels:
          - service=websocket
        addr: 3011
```

And when I run `ngrok start --all`, I see `tcp` for the website instead of `http`:
```
(service=websocket) -> tcp://localhost:3011
(service=website) -> tcp://localhost:3011 <---- not http
```

Is that correct?

**Comment by russorat** [comment]
@cardinal-II since they are using the same port (sorry, i didn't pick up in that sooner), can you just serve everything with a single http tunnel? 

Like, ignore all the stuff i wrote before and just try the following in your config:

```
version: "2"
authtoken: 2Wn
tunnels:
  website:
    addr: 3011
    proto: http
    domain: abc.ngrok-free.app
```

The requests to the website will be handled as normal https traffic, the requests to the websocket path will be handled as a websocket.

**Comment by cardinal-II** [comment]
> can you just serve everything with a single http tunnel?

No, I can't. I got the same error: Firefox can’t establish a connection to the server at wss://abc.ngrok-free.app/. And the app doesn't work properly.

**Comment by inconshreveable** [comment]
does `wss://abc.ngrok-free.app/websocket` work when you have just a single tunnel?

**Comment by inconshreveable** [comment]
ngrok should support websockets as well without any special configuration: https://ngrok.com/docs/http/#websockets

can you provide: a minimal version of the server code which replicates this issue? (maybe in a github repository)

if we can replicate the error we should be able to track down where the bug or misconfiguration is

**Comment by cardinal-II** [comment]
[min_repo](https://github.com/cardinal-II/Vue.js-Node.js-WebSocket)

**Comment by russorat** [comment]
Hi @cardinal-II, I set up your project locally and noticed at least in development, it is using two different ports (5174 for the front and 3011 for the back). I was able to get it working by starting both the front and backend and then using `ngrok http 5174` to get a public address for the frontend. 

![image](https://github.com/user-attachments/assets/09c6db5a-14fe-4156-9574-36f3f17bad30)

**Comment by russorat** [comment]
@cardinal-II since we haven't heard from you in a while, i'm going to close this. if you're still having problems, please open a new issue. thanks!

**Comment by smhanov** [comment]
This issue was clearly caused by https://github.com/ngrok/ngrok/issues/46

I suspect websockets are no longer supported by ngrok using free accounts made after 2022.

Note the russorat's URL is of the form 80350a4eafca.ngrok.app, not the xxx-xxxx-xxxx-xxxx.ngrok-free.app form, indicating that his account will not have the pre-visit page shown.
