### ISSUE TITLE
Ngrok spams endpoints, making it potentially impossible to use

### ISSUE THREAD

**Issue by crawlchange** [ngrok/ngrok#26]
Every time grok is run, either client side or client side, it creates a new endpoint, like this:

"https://df07-34-122-155-174.ngrok-free.app"

The endpoint is always different, so server side and client side cannot connect, since they don't use the same endpoint. If the client is launched, ngrok creates an endpoint. If the server is launched, ngrok creates a DIFFERENT endpoint, for the same agent.

You need to add a cli argument to specify the endpoint, like this:

ngrok http 8080 --endpoint "https://df07-34-122-155-174.ngrok-free.app"

Otherwise, please provide instructions on how to run ngrok at all. Thank you.

**Comment by nijikokun** [comment]
Hi @crawlchange 👋  Glad to see that you have successfully gotten an endpoint and url!

However it seems like you're having trouble because the endpoint url keeps changing when you stop the agent and restart the agent. To fix this, [you can go into your dashboard and claim your static domain](https://ngrok.com/blog-post/free-static-domains-ngrok-users) which you can then use to avoid having it restart across restarts.

Hopefully this helps, the post I linked also includes instructions on how to use the domain as well with both the CLI and SDKs. Let me know if you need any additional help.

**Comment by russorat** [comment]
@crawlchange thanks for the issue. I'm going to assume you got your static endpoint working. if you are still having problems, please open a new issue.
