### ISSUE TITLE
Ngrok fails to read token correctly

### ISSUE THREAD

**Issue by spotlesscoder** [ngrok/ngrok#34]
I installed ngrok on a fresh machine

After running `ngrok config add-authtoken <my-token>` I ran `ngrok http http://localhost:3333` and got the error
```
ERROR:  Error reading configuration file '/home/node/.config/ngrok/ngrok.yml': YAML parsing error: yaml: unmarshal errors:
ERROR:    line 2: field authtoken not found in type config.v3yamlConfig
```

At first glance, the yaml file looks syntactically correct and complete

```
version: "3"
authtoken: <my-token>
```

ngrok version: 3.15.0

**Comment by russorat** [comment]
@spotlesscoder thanks for the issue. we found major issues in 3.15 and had to revert them in 3.15.1. We are working on addressing and will roll out a new version early next week. 

if you upgrade to 3.15.1, you may need to update your ngrok config version to be 2 instead of 3. you can do that with the `ngrok config edit` command.
