### ISSUE TITLE
NGROK_ERR_8000

### ISSUE THREAD

**Issue by ameen-roayan** [ngrok/ngrok#45]
C:\Users\vx_10>ngrok diagnose
Testing ngrok connectivity...

Internet Connectivity
  Name Resolution                           [ OK ]
  TCP                                       [ OK ]
  TLS                                       [ OK ]
Localhost Connectivity
  Name Resolution                           [ OK ]
Ngrok Connectivity - Region: Auto (lowest latency)
  Name Resolution                         [ WARN ]
  TCP                                       [ OK ]
  TLS                                       [ OK ]
  Tunnel Protocol                           [ OK ]
Successfully established ngrok connection! (region: 'auto', latency: unknown)

Warnings and non-fatal errors encountered during diagnostics:

* Diagnostics
  * Name Resolution
    * Resolver: system
      * Hostname: connect.ngrok-agent.com
        - Err: Failed to resolve host connect.ngrok-agent.com: lookup
               connect.ngrok-agent.com: no such host
               (NGROK_ERR_8000)

Report written to C:\Users\vx_10\AppData\Local\Temp\ngrok-diagnose512093328/diagnose.json

any idea why this is happening ? i can no longer connect to anything Ngrok

**Comment by russorat** [comment]
Hi @ameen-roayan, thanks for the issue. usually this is due to something blocking the connection to connect.ngrok-agent.com. It's either your DNS provider or possibly some firewall software running on your system. 

If it is DNS, you can try setting custom DNS resolvers to see if that helps: https://ngrok.com/docs/agent/#dns-resolution

You can also try setting your `connect_url` (`server_addr` if using config version 2) to be one of these: https://ngrok.com/docs/guides/securing-your-tunnels/#blocking-non-corporate-accounts

**Comment by russorat** [comment]
hi @ameen-roayan , any luck?

**Comment by russorat** [comment]
Hi, I'm going to go ahead and close this for now. If you are still having trouble getting this going, please let us know and open an new issue. Thank you!
